### PR TITLE
Stash Serializer

### PR DESCRIPTION
**Pull request by Nyan11**

### CODE REVIEW

**Comment by labordep** [comment]
Thanks @Nyan11, there is a problem with files encoding?
Is this Tonel v1?

**Comment by Nyan11** [comment]
> Thanks @Nyan11, there is a problem with files encoding? Is this Tonel v1?

I have no idea ...

**Comment by labordep** [comment]
This is Tonel v3, please send a pr in Tonel v1.

**Comment by Nyan11** [comment]
See #17

**Pull request closed without merging**
